SCENARIOS = {
    "nifty_bullish_lrhr": {
        "id": "nifty_bullish_lrhr",
        "title": "Nifty bullish LRHR pullback",
        "description": "Bullish HH/HL structure, above 200 EMA, acceptable retracement, and calm execution state.",
        "market_context": {
            "symbol": "NIFTY",
            "timeframe": "5m",
            "last_price": 22500,
            "recent_low": 22420,
            "recent_high": 22620,
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 50.0,
            "distance_from_ema_pct": 0.7,
            "higher_timeframe_bias": "bullish",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "calm",
            "adx": 24,
        },
        "expected_stance": "long_bias",
    },
    "nifty_extended_wait": {
        "id": "nifty_extended_wait",
        "title": "Nifty extended after fast move",
        "description": "Bullish context but price is too far from EMA for fresh chase entry.",
        "market_context": {
            "symbol": "NIFTY",
            "timeframe": "5m",
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 38.2,
            "distance_from_ema_pct": 2.1,
            "higher_timeframe_bias": "bullish",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "calm",
            "adx": 25,
        },
        "expected_stance": "wait",
    },
    "nifty_no_invalidation_wait": {
        "id": "nifty_no_invalidation_wait",
        "title": "Nifty waits without predefined invalidation",
        "description": "Even with bullish confluence, the setup waits if no stop or price-action invalidation level is known.",
        "market_context": {
            "symbol": "NIFTY",
            "timeframe": "5m",
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 50.0,
            "distance_from_ema_pct": 0.7,
            "higher_timeframe_bias": "bullish",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "calm",
            "adx": 24,
        },
        "expected_stance": "wait",
    },
    "nifty_shallow_retracement_wait": {
        "id": "nifty_shallow_retracement_wait",
        "title": "Nifty shallow pullback wait",
        "description": "Bullish structure and EMA bias are present, but retracement is too shallow for a JustNifty LRHR entry.",
        "market_context": {
            "symbol": "NIFTY",
            "timeframe": "5m",
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 20.0,
            "distance_from_ema_pct": 0.6,
            "higher_timeframe_bias": "bullish",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "calm",
            "adx": 24,
        },
        "expected_stance": "wait",
    },
    "nifty_mixed_mtf_wait": {
        "id": "nifty_mixed_mtf_wait",
        "title": "Nifty mixed higher-timeframe wait",
        "description": "Local bullish setup waits when higher-timeframe bias is mixed instead of aligned.",
        "market_context": {
            "symbol": "NIFTY",
            "timeframe": "5m",
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 50.0,
            "distance_from_ema_pct": 0.6,
            "higher_timeframe_bias": "mixed",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "calm",
            "adx": 24,
        },
        "expected_stance": "wait",
    },
    "banknifty_bullish_profile": {
        "id": "banknifty_bullish_profile",
        "title": "BankNifty bullish profile-adjusted setup",
        "description": "BankNifty allows wider EMA extension than Nifty while still requiring adequate ADX.",
        "market_context": {
            "symbol": "BANKNIFTY",
            "timeframe": "5m",
            "last_price": 48200,
            "recent_low": 48040,
            "recent_high": 48550,
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 50.0,
            "distance_from_ema_pct": 1.8,
            "higher_timeframe_bias": "bullish",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "calm",
            "adx": 24,
        },
        "expected_stance": "long_bias",
    },
    "banknifty_choppy_wait": {
        "id": "banknifty_choppy_wait",
        "title": "BankNifty low ADX wait",
        "description": "BankNifty context is structurally bullish but ADX is below the BankNifty threshold.",
        "market_context": {
            "symbol": "BANKNIFTY",
            "timeframe": "5m",
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 50.0,
            "distance_from_ema_pct": 1.4,
            "higher_timeframe_bias": "bullish",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "calm",
            "adx": 18,
        },
        "expected_stance": "wait",
    },
    "banknifty_bearish_mtf_entry_structure_wait": {
        "id": "banknifty_bearish_mtf_entry_structure_wait",
        "title": "BankNifty bearish MTF waits for entry structure",
        "description": "Higher timeframes are bearish, but the entry timeframe must still show LH/LL before a short setup is allowed.",
        "market_context": {
            "symbol": "BANKNIFTY",
            "timeframe": "5m",
            "market_structure": "sideways",
            "price_above_ema200": False,
            "retracement_pct": 50.0,
            "distance_from_ema_pct": 1.1,
            "higher_timeframe_bias": "bearish",
            "higher_timeframe_agreement": "aligned",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": False,
            "emotional_state": "calm",
            "adx": 24,
        },
        "expected_stance": "neutral_wait",
    },
    "banknifty_revenge_block": {
        "id": "banknifty_revenge_block",
        "title": "BankNifty revenge-trading block",
        "description": "Even when structure is favorable, revenge state blocks the setup.",
        "market_context": {
            "symbol": "BANKNIFTY",
            "timeframe": "5m",
            "market_structure": "HH_HL",
            "price_above_ema200": True,
            "retracement_pct": 50.0,
            "distance_from_ema_pct": 1.0,
            "higher_timeframe_bias": "bullish",
            "at_channel_or_envelope_extreme": False,
            "core_tools_aligned": True,
            "emotional_state": "revenge",
            "adx": 25,
        },
        "expected_stance": "wait",
    },
}


def list_scenarios() -> list[dict]:
    return list(SCENARIOS.values())


def get_scenario(scenario_id: str) -> dict | None:
    return SCENARIOS.get(scenario_id)
